"""
Django settings for premiacion project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Establece la ruta base del proyecto, en este caso la ruta de la carpeta premiacion que contiene el archivo settings.py
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k+x!@l)$756(@b^u*&4e0q!-sbm^t7nzzhx@a^=+yq0(b5+lns'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "polls.apps.PollsConfig", # Agrega la aplicación polls al proyecto

    'django.contrib.admin', # Administra las aplicaciones instaladas en el proyecto (usuarios, grupos, etc.)
    'django.contrib.auth', # Administra la autenticación de usuarios (login, logout, etc.)
    'django.contrib.contenttypes', # Administra los tipos de contenido de las aplicaciones instaladas en el proyecto (usuarios, grupos, etc.)
    'django.contrib.sessions', # Administra las sesiones de los usuarios
    'django.contrib.messages', # Administra los mensajes de las aplicaciones (errores, mensajes de éxito, etc.)
    'django.contrib.staticfiles', # Administra los archivos estáticos de las aplicaciones (CSS, JavaScript, imágenes, etc.)
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'premiacion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'premiacion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Establece la configuración de la base de datos a utilizar en el proyecto, en este caso SQLite, pero puede ser MySQL, PostgreSQL, Oracle, etc.
DATABASES = {
    'default': {
        # Establece el motor de base de datos a utilizar
        'ENGINE': 'django.db.backends.sqlite3',
        # Establece el nombre de la base de datos, en este caso db.sqlite3
        'NAME': BASE_DIR / 'db.sqlite3',
        # Posteriormente se pueden definir los parámetros de conexión a la base de datos, como el usuario, contraseña, host, puerto, etc. con:
        # 'USER': 'user',
        # 'PASSWORD': 'password',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Lista de zonas horarias soportadas por Django, para más información consultar:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones (ver la segunda columna)
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# URL de los archivos estáticos (CSS, JavaScript, imágenes, etc.)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
